### ISSUE TITLE
When I enable the extension, the website breaks.

### ISSUE THREAD

**Issue by dalvan03** [arrowhitech-gp/magento2-cms-builder#2]
I followed the 4 steps described on your webbsite and after activating the extension via SSH, my website breaks, no longer opens and shows error 500. When I deactivate, the website goes back to work.

Notice: Undefined index: id in /home/u225447137/domains/nictarpod.com.br/public_html/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 63

    public function setElements(array $elements, $scope)
    {
        $this->_elements = $elements;
        $this->_scope = $scope;
        if (count($elements)) {
            $lastElement = end($elements);
            $this->_lastId = $lastElement['id'];    <-----this is line 63
        }
    }

**Comment by dalvan03** [comment]
Notice: Undefined index: id in /home/u225447137/domains/nictarpod.com.br/public_html/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 63

**Comment by arrowtheme2022** [comment]
Hi,

Sorry for missing your comment.
Did you install MGS_Core module ?

**Comment by dalvan03** [comment]
No, I didnt. But I have Porto Theme installed. Maybe it could be that? 
Or is MGS_Core a requirement?

**Comment by arrowtheme2022** [comment]
To install our extension, you need to install MGS_Core module first.
Please download it here: https://github.com/arrowhitech-gp/core
