### ISSUE TITLE
css files doesn't exist

### ISSUE THREAD

**Issue by tarekfellah** [arrowhitech-gp/magento2-cms-builder#4]
For this free version some css files doesn't exist 
`<link  rel="stylesheet" type="text/css" media="all" href="<?php echo $this->getMediaUrl() ?>mgs/fbuilder/css/blocks.min.css" />
<link  rel="stylesheet" type="text/css" media="all" href="<?php echo $this->getMediaUrl() ?>mgs/fbuilder/css/<?php echo $this->getStoreId() ?>/fbuilder_config.min.css" />`
blocks.min.css and fbuilder_config.min.css doesn't exist in pub/media/mgs/fbuilder/css

**Comment by arrowtheme2022** [comment]
Hi,

The css files will automatic generate when you save config in backend and when you save builder blocks on front-end.
