### ISSUE TITLE
TypeError: $(...).attr(...).mColorPicker is not a function

### ISSUE THREAD

**Issue by jg-development** [arrowhitech-gp/magento2-cms-builder#5]
I installed the free version and in the backend settings I get a console error with:
TypeError: $(...).attr(...).mColorPicker is not a function

I am using the actual version

**Comment by arrowtheme2022** [comment]
Hi jg-development,

Maybe our extension conflict with other extension or theme's configuration existing on your site.
Please try to edit this file: app\code\MGS\Fbuilder\Block\Adminhtml\Fields
remove below code:
`$output .= "
		<script type='text/javascript'>
			require([
				'jquery'
			], function(jQuery){
				(function($) {
					$('#".$element->getHtmlId()."').attr('data-hex', true).mColorPicker();
				})(jQuery);
			});
		</script>";`

**Comment by jg-development** [comment]
After a new install this issue seems to be resolved.
thx
