### ISSUE TITLE
Undefined property: MGS\Fbuilder\Block\Page\Head::$_generateHelper

### ISSUE THREAD

**Issue by jian-sun** [arrowhitech-gp/magento2-cms-builder#6]
after installed
open front home page
error message: Undefined property: MGS\Fbuilder\Block\Page\Head::$_generateHelper

class Head extends Template
{	
	protected $_scopeConfig;
	protected $_storeManager;
	public function __construct(
        Context $context,
		\Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig
    )
    {       
		$this->_scopeConfig = $scopeConfig;
		$this->_storeManager = $context->getStoreManager();
        parent::__construct($context);
    }
	
	public function getStoreConfig($node, $storeId = NULL){
		return $this->_generateHelper->getStoreConfig($node);
	}

**_generateHelper** is Undefined

**Comment by aethatsme** [comment]
I have the same issue. 

I was able to get the page to load by updating Head.php file to a previous commit.
/* Newest Commit
	public function getStoreConfig($node, $storeId = NULL){
		return $this->_generateHelper->getStoreConfig($node);
	}
	
	public function getMediaUrl(){
		return $this ->_storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA );
	}
	
	public function getStoreId(){
		return $this ->_storeManager->getStore()->getId();
	}
	*/
	
	/* Previous Version */
	public function getStoreConfig($node, $storeId = NULL){
		if($storeId != NULL){
			return $this->_scopeConfig->getValue($node, \Magento\Store\Model\ScopeInterface::SCOPE_STORE, $storeId);
		}
		return $this->_scopeConfig->getValue($node, \Magento\Store\Model\ScopeInterface::SCOPE_STORE, $this->_storeManager->getStore()->getId());
	}

**Comment by arrowtheme2022** [comment]
Hi, 
Sorry for later reply. We have fixed the issue.
